commands:
  eval:
    enabled: false
    example: eval [page]
    function: evaluate
    help: evaluate an expression
    rank: '~'
  join:
    enabled: true
    example: pm [user], [message]
    function: join
    help: PM a user a message
    rank: '~'
  leave:
    enabled: true
    example: leave [room]
    function: leave
    help: leave a room
    rank: '~'
  man:
    enabled: true
    example: man [page]
    function: man
    help: get man page info
    rank: +
  permission:
    enabled: true
    example: permission [command], [newRank]
    function: permission
    help: Change permissions on a command
    rank: '~'
  pm:
    enabled: false
    example: pm [user], [message]
    function: pm
    help: PM a user a message
    rank: +
  reload:
    enabled: true
    example: pm [user], [message]
    function: reload
    help: PM a user a message
    rank: '~'
  restart:
    enabled: true
    example: restart
    function: restartBot
    help: leave a room
    rank: '~'
  reverse:
    enabled: true
    example: reverse [string]
    function: reverse
    help: Reverse text
    rank: +
  roll:
    enabled: false
    example: roll
    function: roll
    help: PM a user a message
    rank: +
  say:
    enabled: true
    function: say
    help: Repeat text inputted
    rank: +
    usage: say [text]
  spam:
    enabled: true
    example: permission [command], [newRank]
    function: spam
    help: Change permissions on a command
    rank: '~'
  toggle:
    enabled: true
    example: toggle [command]
    function: toggle
    help: toggles a command (on or off)
    rank: '~'
config:
  autojoin_rooms:
  - kertrio
  blacklisted_users:
  - probablythevodka
  commmand_characters:
  - $
  connection_info:
    imgur:
      clientID: null
      secretID: null
    showdown:
      nickname: Cubic Ninja
      password: ok
      username: cubicninja
    twitter:
      access_token: null
      access_token_secret: null
      api_key: null
      api_secret: null
  whitelisted_users:
  - minnow
  - newvegas
  - cubicninja
